# Intent definition for Yes/no:
#
#  (c) A. Dominik, 2020
#
title = "ADoSnipsYesOrNoDE"


[inventory]
# slot_types = ["yes_or_no_type"]     # predefined types need not to be declared:
#                                     # any/date/time/datetime/currency/...
slots = ["yes_or_no", "begin", "end"]
intents = "ADoSnipsYesOrNo"


# define slots:
# Types: any/list/datetime/currency/number/ordinal/...
#
[yes_or_no]
slot_type = "list"
synonyms = ["NO" = ["nein", "nö", "nicht", "auf keinen Fall", "Abbruch", "abbrechen",
                    "ende", "exit"],
            "YES" = ["ja", "jawohl", "ja doch", "natürlich", "sowieso", "mach",
                     "mach es", "tu es", "weiter", "mehr", "sicher"]]

[begin]
slot_type = "date"

[end]
slot_type = "date"


# define phrases for intent recognition:
# exact, regex, part
#
[ADoSnipsYesOrNo]
minimal = "exact: <yes_or_no>"
please = "exact: <> <yes_or_no> <>"
all_in_one = "regex: ^(?bitte|) <yes_or_no> (?bitte|)$"
tolerant = "partial: <yes_or_no>"
